server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie
      timeout: 30m

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.35.210.214:3306/positionback?serverTimezone=Asia/Seoul
    username: gb
    password: 1234

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
      file-size-threshold: 30MB

mybatis:
  config-location: classpath:/config/config.xml
  mapper-locations: classpath*:/mapper/*.xml